# Generated by Django 5.0.14 on 2025-04-10 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=20, unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Scheme Detail',
                'verbose_name_plural': 'Scheme Details',
                'ordering': ['scheme_name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=10)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='mf_app.schemedetails')),
            ],
            options={
                'ordering': ['nav_date'],
                'unique_together': {('scheme', 'nav_date')},
            },
        ),
    ]
