# Generated by Django 5.0.14 on 2025-04-12 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('scheme_code', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'Scheme_Details',
            },
        ),
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_date', models.DateField()),
                ('nav', models.FloatField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='mf_app.schemedetails')),
            ],
            options={
                'db_table': 'MutualFund_NAV',
                'unique_together': {('scheme', 'nav_date')},
            },
        ),
    ]
