# Generated by Django 5.0.14 on 2025-04-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mutualfundnav',
            index=models.Index(fields=['scheme', 'nav_date'], name='mf_app_mutu_scheme__929f22_idx'),
        ),
    ]
